### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lukasoppermann** [worddrop/bookworm#16]
Hey @jeroenvisser101 can you create a new release? Thanks.

**Comment by jeroenvisser101** [comment]
@lukasoppermann since you're a contributor, you should be able to do this yourself now, if I'm correct. :)

**Comment by lukasoppermann** [comment]
Yes, true, I just was not sure if this is fine by you. :)

**Comment by jeroenvisser101** [comment]
Sure, just stick by semver :)
