### ISSUE TITLE
Update regex to not strip everything

### ISSUE THREAD

**Issue by lukasoppermann** [worddrop/bookworm#2]
Hey, what are you trying to achieve with `$words = trim(preg_replace('/[^\w0-9]+/i', ' ', $text));` https://github.com/worddrop/bookworm/blob/master/src/Bookworm/Bookworm.php#L81 ?

It currently trips everything, this means if you feed it html with code tags and `&lt;table&gt; &lt;/table&gt;` you get `lt table gt lt table gt` which will lead to a messed up count. 

Personally I think we should expect:
- plain text
- html
- markdown

as an input and try to deal with this by adapting the regex here.

**Comment by jeroenvisser101** [comment]
We could say that we have a `Tokenizer` that is a injectable class that converts the input into tokens, tokens that you can then count? You could make tokenizers for Markdown, HTML, or just plain text, or even a custom one if you'd like.

**Comment by lukasoppermann** [comment]
So you are saying we could refactor it to use a Tokenizer? Sounds like a pretty good idea. Do you already have an idea how you want to implement it?

**Comment by jeroenvisser101** [comment]
Yeah, that's what I was thinking about. I think you could have the current one (so we don't break BC) as default, and call `$bookworm->setTokenizer(TokenizerInterface $tokenizer)` to set a tokenizer (or maybe inject it in the contructor?)

**Comment by lukasoppermann** [comment]
I don't think a BC break would be a problem, as you are on version `0.1`.

Anyway, the current one is meant for plain text, correct? This could not be broken in any case, as it should work fine for markdown and html.

However, I am not sure, we actually need 3 Tokenizer. Wouldn't an html/markdown tokenzier be enough? It must definitely handle plain text fine as both html & markdown just add stuff on top. Also Markdown supports html tags, so all we need to do to jump form html to markdown, is work in images and code blocks.

I would think we should add a `standard` tokenizer which handles plain, html & standard markdown and anybody who needs more, can write a custom tokenizer.

`$bookworm->setTokenizer(TokenizerInterface $tokenizer)` should be fine as most people will probably not change it, so a constructor injection would be an overkill IMO.

**Comment by jeroenvisser101** [comment]
This issue can be marked as resolved, right?

**Comment by lukasoppermann** [comment]
Not really, as the regex is still untouched. I thought you wanted to add a tokenizer?

**Comment by lukasoppermann** [comment]
Maybe we can replace it with the php `strip_tags` function. We would just need to deal with code sections.

Do you think code sections have a different reading time? Should that be allowed?

**Comment by lukasoppermann** [comment]
Fixed in #11.
