### ISSUE TITLE
Return time in minutes without text.

### ISSUE THREAD

**Issue by lukasoppermann** [worddrop/bookworm#4]
I want to use the time in a `<time>` element so I need the time without minutes or min. I think this packages should be capable of returning the time in minutes without the text as well.

On a related note, why do you have the short and long type and translations, don't you think it is an overkill? Why not just pass either a text string or `false` as the second argument, and use this?

**Comment by jeroenvisser101** [comment]
I thought translations as they are implemented are the easiest way to re-use it. Since there's pluralisation and things like that happening, I'd thought it made the most sense.

For the `TYPE_NONE`, I really like it, good job :+1:

**Comment by lukasoppermann** [comment]
But you are not doing pluralisation, correct? 

We could have the user add a string, or an array if there is a plural, like this:

``` php
# singular
$readingTime = Bookworm::estimate($story, 'min'); // 1 min or 8 min
# plural
$readingTime = Bookworm::estimate($story, ['minute','minutes']); // 1 minute or 8 minutes
# none
$readingTime = Bookworm::estimate($story, false); // 1 or 8
```

The default could be either min or minute and minutes, both would be fine.

**Comment by jeroenvisser101** [comment]
I like that, if you make a PR I'll merge it :)
